### ISSUE TITLE
href='#"

### ISSUE THREAD

**Issue by UisgeBeatha436** [bernydole/vanillatop#2]
Hi,
A strange thing happens when the link to go to the top of is clicked; if one is not on the homepage, than the page reloads (happens in all cases), but the site also loads the homepage instead of staying on the same page. 

Is there a way to solve this behaviour?

Thanks!

**Comment by bernydole** [comment]
Hi,
Use the following syntax:
`<a href="#!" class="vanillatop"></a>`

Best Regards.

**Comment by UisgeBeatha436** [comment]
Thanks. That did the trick.
