### ISSUE TITLE
Moving slow

### ISSUE THREAD

**Issue by oleteacher** [bernydole/vanillatop#3]
Hey, great javascript only solution!

Have a rather large one page site (for a software documentation) and after clicking the return to top button, really slow scrolling.

Is there any settings which control scroll speed? Using the cdn unpkg and latest version of your script.

Thank you!

**Comment by bernydole** [comment]
Thank you.
I prefer having variables hard written in the script to allow easy integration. If you need to change the speed you have to use the git version of the script to allow you modifying the variables.

**Comment by oleteacher** [comment]
Sorry to have bothered you with a question. We are using in a classroom project and will look else here.
